"""Audit the checked-in Baseline Profile text rules against the *current* compiled
signatures of this app.

Why this exists
---------------
ART profile rules match literally: `Lcom/…;->name(param-descs)ret-desc`. The moment a
signature changes (renamed, moved to another class, parameter list touched) the rule
stops matching, and R8 drops it **silently** — the build stays green, the profile just
gets smaller than everyone thinks. So "is the profile still worth anything" is a
measurable number, not an opinion.

Method
------
Ground truth = the method/class signature set of the app's own DEX. DEX is authoritative
for "what does the source compile to right now" (name *and* full parameter descriptor),
which a source grep cannot answer for Kotlin (default args, inline, `$N` overloads,
Compose synthetics). The DEX is parsed here directly — no external toolchain needed.

Rule classification (per unique `class->name(desc)ret`, flags ignored):
  alive              exact signature present in the current DEX
  sig-changed        class + method name present, descriptor absent
  name-gone          class present in the DEX, that method name absent
  class-gone         class descriptor absent from the DEX
  not-in-this-dex    no `Lcom/buaa/schedule/` class was defined at all (guard against
                     pointing the script at the wrong APK)

Anything but `alive` counts as dead.

Usage
-----
  python docs/tools/profile_audit.py \
      --profile app/src/release/generated/baselineProfiles/baseline-prof.txt \
      --profile app/src/release/generated/baselineProfiles/startup-prof.txt \
      --apk app/build/outputs/apk/debug/app-debug.apk \
      --out .tmp/T79/audit-before.md

`--apk` may be given several times; the signature sets are unioned.
"""

import argparse
import re
import struct
import sys
import zipfile

APP_PREFIX = 'Lcom/buaa/schedule/'

# Kotlin mangles every `internal` member name with the **module name**, and AGP's module
# name carries the variant: `foo$app_debug` vs `foo$app_release` vs `foo$app_nonMinifiedRelease`.
# A profile text generated by one variant therefore cannot match another, no matter how
# little the source moved. Normalising the token lets the audit tell that apart from
# "someone actually renamed my function".
MODULE_TOKEN = re.compile(r'\$app_[A-Za-z0-9]+')


def normalise(sig):
    return MODULE_TOKEN.sub('$app_*', sig)


# ART flag chars are a prefix of "HSPL", then the class descriptor.
RULE_RE = re.compile(r'^([HSP]*)(L[^;]+;)(?:->([^(]+)\(([^)]*)\)(\S+))?$')


def read_uleb128(buf, off):
    result = 0
    shift = 0
    while True:
        b = buf[off]
        off += 1
        result |= (b & 0x7F) << shift
        if not b & 0x80:
            return result, off
        shift += 7


class Dex:
    """Only the parts needed to rebuild `cls;->name(params)ret` strings."""

    def __init__(self, blob):
        if blob[:4] != b'dex\n':
            raise ValueError('not a DEX file (magic=%r)' % blob[:8])
        endian = struct.unpack_from('<I', blob, 40)[0]
        if endian != 0x12345678:
            raise ValueError('unsupported endian tag 0x%08x' % endian)
        (self.string_size, self.string_off, self.type_size, self.type_off,
         self.proto_size, self.proto_off, self.field_size, self.field_off,
         self.method_size, self.method_off, self.classdef_size,
         self.classdef_off) = struct.unpack_from('<12I', blob, 56)
        self.blob = blob
        self._strings = None
        self._types = None

    def strings(self):
        if self._strings is None:
            out = []
            for i in range(self.string_size):
                data_off = struct.unpack_from('<I', self.blob, self.string_off + 4 * i)[0]
                _n, p = read_uleb128(self.blob, data_off)
                end = self.blob.index(b'\0', p)
                # MUTF-8 is UTF-8 for every code point this project can produce
                # (no embedded NUL, surrogate pairs are CESU-8 -> decode tolerantly)
                out.append(self.blob[p:end].decode('utf-8', 'replace'))
            self._strings = out
        return self._strings

    def types(self):
        if self._types is None:
            s = self.strings()
            self._types = [
                s[struct.unpack_from('<I', self.blob, self.type_off + 4 * i)[0]]
                for i in range(self.type_size)
            ]
        return self._types

    def _params(self, proto_idx):
        blob = self.blob
        parameters_off = struct.unpack_from('<I', blob, self.proto_off + 12 * proto_idx + 8)[0]
        if not parameters_off:
            return ''
        # list_item's size field is a full u4, not a uleb128 (that's string_data_item)
        size = struct.unpack_from('<I', blob, parameters_off)[0]
        p = parameters_off + 4
        types = self.types()
        out = []
        for _ in range(size):
            out.append(types[struct.unpack_from('<H', blob, p)[0]])
            p += 2
        return ''.join(out)

    def signatures(self):
        """Set of `Lcls;->name(params)ret` for every method defined anywhere in this dex."""
        blob = self.blob
        strings, types = self.strings(), self.types()
        out = set()
        for i in range(self.method_size):
            class_idx, proto_idx = struct.unpack_from('<2H', blob, self.method_off + 8 * i)
            name_idx = struct.unpack_from('<I', blob, self.method_off + 8 * i + 4)[0]
            return_off = self.proto_off + 12 * proto_idx + 4
            ret = types[struct.unpack_from('<I', blob, return_off)[0]]
            out.add('%s->%s(%s)%s' % (types[class_idx], strings[name_idx],
                                      self._params(proto_idx), ret))
        return out

    def defined_classes(self):
        blob = self.blob
        types = self.types()
        return {
            types[struct.unpack_from('<I', blob, self.classdef_off + 32 * i)[0]]
            for i in range(self.classdef_size)
        }


def load_apk(path):
    sigs, classes = set(), set()
    with zipfile.ZipFile(path) as zf:
        names = [n for n in zf.namelist() if re.fullmatch(r'classes\d*\.dex', n)]
        if not names:
            raise ValueError('%s contains no dex' % path)
        for name in sorted(names):
            dex = Dex(zf.read(name))
            sigs |= dex.signatures()
            classes |= dex.defined_classes()
    return sigs, classes, names


def parse_profiles(paths):
    """-> {signature: {'class':…, 'name':…, 'file':set(), 'flags':set()}} ; signature is
    `Lcls;->name(desc)ret` for methods and `Lcls;` for plain class rules."""
    rules = {}
    for path in paths:
        label = path.replace('\\', '/').rsplit('/', 1)[-1]
        with open(path, encoding='utf-8') as fh:
            for raw in fh:
                line = raw.strip()
                if not line or line.startswith('#'):
                    continue
                m = RULE_RE.match(line)
                if not m:
                    continue
                flags, cls, name, params, ret = m.groups()
                if not cls.startswith(APP_PREFIX):
                    continue
                key = cls if name is None else '%s->%s(%s)%s' % (cls, name, params, ret)
                ent = rules.setdefault(key, {'class': cls, 'name': name, 'files': set(),
                                             'flags': set()})
                ent['files'].add(label)
                ent['flags'].add(flags)
    return rules


def classify(rules, sigs, classes):
    """Index the dex once, then each rule is O(1).

    `by_member` answers "does this class have a method of this *name* at all", which is
    what separates "the parameter list moved" from "the method is gone / moved class".
    """
    by_member = {}
    for s in sigs:
        head, _, tail = s.partition('->')
        by_member[(head, tail.split('(')[0])] = by_member.get((head, tail.split('(')[0]), 0) + 1
    sigs_norm = {normalise(s) for s in sigs}
    for key, ent in rules.items():
        if ent['name'] is None:
            ent['state'] = 'alive' if ent['class'] in classes else 'class-gone'
        elif key in sigs:
            ent['state'] = 'alive'
        elif normalise(key) in sigs_norm:
            # only the Kotlin internal-mangling token differs — same source, other variant
            ent['state'] = 'variant-suffix'
        elif (ent['class'], ent['name']) in by_member:
            ent['state'] = 'sig-changed'
        elif ent['class'] in classes:
            ent['state'] = 'name-gone'
        else:
            ent['state'] = 'class-gone'
    return rules


def family(cls):
    """Package tail, so 'dead where?' is readable."""
    parts = cls[len('L'):].split('/')
    return '/'.join(parts[1:-1]) if len(parts) > 2 else '(root)'


# Buckets, in reporting order. Everything here is a name the *compiler* invented, so a
# miss in this bucket is "the build shifted", not "someone renamed my function" — which is
# exactly why the hand-written number is the one that hurts.
SYNTHETIC = (
    ('synthetic-lambda-class',
     re.compile(r'\$\$?(External|Internal)Synthetic.*Lambda\D*\d+$')),
    ('r8-lambda-method', re.compile(r'->\$r8\$lambda\$')),
    ('compose-singleton', re.compile(r'ComposableSingletons\$')),
    ('when-mappings', re.compile(r'\$WhenMappings;?$')),
    ('kotlin-serializer', re.compile(r'\$\$serializer;?$')),
    ('anon-class', re.compile(r'\$\d+;?$')),
)


def bucket(cls, key):
    """Which name did the compiler invent? Class descriptors end in ';', so the anchors
    below are checked against the stripped form."""
    bare = cls[:-1] if cls.endswith(';') else cls
    for name, rx in SYNTHETIC:
        if rx.search(key) or (name != 'r8-lambda-method' and rx.search(bare)):
            return name
    return 'source'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--profile', action='append', required=True)
    ap.add_argument('--apk', action='append', required=True)
    ap.add_argument('--out')
    ap.add_argument('--top', type=int, default=45)
    args = ap.parse_args()

    sigs, classes, dexnames = set(), set(), []
    for apk in args.apk:
        s, c, n = load_apk(apk)
        sigs |= s
        classes |= c
        dexnames.append('%s(%d dex)' % (apk.rsplit('/', 1)[-1], len(n)))
    app_classes = {c for c in classes if c.startswith(APP_PREFIX)}
    if not app_classes:
        print('FATAL: no %s class defined in %s' % (APP_PREFIX, ', '.join(args.apk)))
        return 2

    rules = classify(parse_profiles(args.profile), sigs, classes)
    order = ['alive', 'variant-suffix', 'sig-changed', 'name-gone', 'class-gone']
    counts = {k: 0 for k in order}
    for ent in rules.values():
        counts[ent['state']] += 1
    total = len(rules)
    dead = total - counts['alive']
    code_dead = dead - counts['variant-suffix']

    per_file = {}
    for key, ent in rules.items():
        for f in ent['files']:
            d = per_file.setdefault(f, {'total': 0, 'alive': 0, 'code_dead': 0})
            d['total'] += 1
            d['alive'] += ent['state'] == 'alive'
            d['code_dead'] += ent['state'] not in ('alive', 'variant-suffix')

    lines = []
    w = lines.append
    w('# Baseline Profile rule audit')
    w('')
    w('ground-truth dex: %s' % ', '.join(dexnames))
    w('app classes defined in dex: %d' % len(app_classes))
    w('')
    w('| scope | rules | alive | dead | dead-by-code-change |')
    w('|---|---|---|---|---|')
    for f, d in sorted(per_file.items()):
        w('| %s | %d | %d | %d | %d |'
          % (f, d['total'], d['alive'], d['total'] - d['alive'], d['code_dead']))
    w('| **union (dedup)** | **%d** | **%d** | **%d** | **%d** |'
      % (total, counts['alive'], dead, code_dead))
    w('')
    w('dead-cause split: ' + ' / '.join('%s=%d' % (k, counts[k]) for k in order[1:]))
    w('')
    w('`variant-suffix` = the signature is still in the source, only the Kotlin `internal`')
    w('mangling token differs (`$app_nonMinifiedRelease` in the checked-in text vs the')
    w('variant being built). Regenerating the same way will **not** fix those; they are')
    w('reported separately so the drift number is honest.')
    w('')
    w('## 按稳定度分桶（编译器造的名字单独算一档）')
    w('')
    w('| 桶 | 总数 | 命中 | 仅变体后缀 | 已死(源码变动) |')
    w('|---|---|---|---|---|')
    bk = {}
    for key, ent in rules.items():
        d = bk.setdefault(bucket(ent['class'], key),
                          {'total': 0, 'alive': 0, 'variant': 0})
        d['total'] += 1
        d['alive'] += ent['state'] == 'alive'
        d['variant'] += ent['state'] == 'variant-suffix'
    for name in sorted(bk, key=lambda k: (k != 'source',
                                          -(bk[k]['total'] - bk[k]['alive'] - bk[k]['variant']))):
        d = bk[name]
        w('| %s | %d | %d | %d | %d |'
          % (name, d['total'], d['alive'], d['variant'],
             d['total'] - d['alive'] - d['variant']))
    src = bk.get('source', {'total': 0, 'alive': 0, 'variant': 0})
    w('')
    w('**只算手写代码（source 桶）**: 总数 %d / 命中 %d / 仅变体后缀 %d / 已死 %d（%.1f%%）'
      % (src['total'], src['alive'], src['variant'],
         src['total'] - src['alive'] - src['variant'],
         100.0 * (src['total'] - src['alive'] - src['variant']) / max(src['total'], 1)))
    w('')
    w('## 按包族统计（仅 source 桶，即手写类与其方法）')
    w('')
    w('| 包族 | 总数 | 命中 | 仅变体后缀 | 已死(源码变动) |')
    w('|---|---|---|---|---|')
    fam = {}
    for key, ent in rules.items():
        if bucket(ent['class'], key) != 'source':
            continue
        d = fam.setdefault(family(ent['class']), {'total': 0, 'alive': 0, 'variant': 0})
        d['total'] += 1
        d['alive'] += ent['state'] == 'alive'
        d['variant'] += ent['state'] == 'variant-suffix'
    for name, d in sorted(fam.items(),
                          key=lambda kv: -(kv[1]['total'] - kv[1]['alive'] - kv[1]['variant'])):
        w('| %s | %d | %d | %d | %d |'
          % (name, d['total'], d['alive'], d['variant'],
             d['total'] - d['alive'] - d['variant']))
    w('')
    w('## 手写代码里死掉的规则（按类名分组）')
    w('')
    for state in ('sig-changed', 'name-gone', 'class-gone'):
        hit = sorted(k for k, e in rules.items()
                     if e['state'] == state and bucket(e['class'], k) == 'source')
        w('### %s (%d)' % (state, len(hit)))
        w('')
        for k in hit[:args.top]:
            w('- `%s`' % k)
        if len(hit) > args.top:
            w('- … 另有 %d 条（全量见 %s.rules.tsv）' % (len(hit) - args.top, args.out))
        w('')

    report = '\n'.join(lines) + '\n'
    # GBK console: write bytes ourselves, never let the locale codec touch this text
    sys.stdout.buffer.write(report.encode('utf-8', 'backslashreplace'))
    if args.out:
        with open(args.out, 'w', encoding='utf-8', newline='\n') as fh:
            fh.write(report)
        with open(args.out + '.rules.tsv', 'w', encoding='utf-8', newline='\n') as fh:
            fh.write('state\tbucket\tpackage\tfile\trule\n')
            for key, ent in sorted(rules.items()):
                fh.write('%s\t%s\t%s\t%s\t%s\n'
                         % (ent['state'], bucket(ent['class'], key), family(ent['class']),
                            ','.join(sorted(ent['files'])), key))
    return 0


if __name__ == '__main__':
    sys.exit(main())
